spring.application.name=FitHub
spring.datasource.url=jdbc:postgresql://localhost:5432/FitHub
spring.datasource.username=sadam
spring.datasource.password=qLUftio3
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true

secret-ket=9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9
token-expiration=3600000
refresh-token-expiration=604800000
# Admin Account
admin-name=Admin
admin-email=admin@fithub.com
admin-username=admin
admin-password=qLUftio3


# Enable debug logging
logging.level.org.springframework.web=DEBUG
#The filename pattern used to create log archives.
logging.logback.rollingpolicy.file-name-pattern=/opt/ecart_logs/%d{yyyy-MM, aux}/app.%d{yyyy-MM-dd}.%i.log

#The maximum size of log file before it is archived.
logging.logback.rollingpolicy.max-file-size=100MB

#The maximum amount of size log archives can take before being deleted.
logging.logback.rollingpolicy.total-size-cap=10GB

#The maximum number of archive log files to keep (defaults to 7).
logging.logback.rollingpolicy.max-history=10

enable-performance-monitoring=true

# Mail Sender
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=adamsdsami@gmail.com
spring.mail.password=tprooygghxwekysa
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Stripe
stripe.api.key=sk_test_51PiP1pJlUpmb5PqMxzapB08FS4quZUWA3bKrIKtrqbBka5yZArHnd7GKuY3IiphljmSuKTFodTpubf5KFn2FdeJ100nxblOERt
stripe.public.key=pk_test_51PiP1pJlUpmb5PqMRt77pcCE8nXf2SjPTMZY01LZc1pEOUdxQywXXquGLWQfB7oMIz8JiCENA9iTNVDJ8TIfjfsO00kxEon4k9


